---

language: python
dist: xenial

python:
  - 2.7
  - 3.5
  - 3.6

matrix:
  fast_finish: true

env:
  matrix:
    - ANSIBLE=2.2
    - ANSIBLE=2.3
    - ANSIBLE=2.4
    - ANSIBLE=2.5
    - ANSIBLE=2.6

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: false
